### ISSUE TITLE
[Feature]: MediaControl / MediaGallery

### ISSUE THREAD

**Issue by tinodin** [ghost1372/DevWinUI#88]
### feature proposal

I want to use your new Card control and inside have a Gallery for Screenshots and Videos like in Microsoft Store.
<img width="1919" height="1033" alt="Image" src="https://github.com/user-attachments/assets/3324f06a-656f-4125-a849-7bbf2b172ebc" />

On item click it should expand into Fullscreen:
<img width="1916" height="1036" alt="Image" src="https://github.com/user-attachments/assets/51b7c560-eaf8-4e87-bd58-3f123b670a95" />

<img width="1919" height="1034" alt="Image" src="https://github.com/user-attachments/assets/ace9fe60-193c-4510-a3e4-59baf86c2fd0" />

It should be able to be opened by a button click event from the card button.

**Comment by tinodin** [comment]
Also in Card.xaml adjust the margin of the Title to be like Microsoft Store which is:
`<TextBlock Margin="24,0,0,0"`

instead of:
`<TextBlock Margin="16,0,0,0"`

**Comment by tinodin** [comment]
No the click event i can get from a custom button inside TitleContent in the Card. I need the gallery which is similar to what you already have for the MainLandingPage ([here](https://github.com/ghost1372/DevWinUI/blob/30a24aa157e755cd9c1bad64f5bd7a6dcb8fdc93/dev/DevWinUI.Controls/LandingPages/TileGallery.xaml)). But it should be able to expand into full screen and support Video (MediaPlayerElement) and Images.

**Comment by tinodin** [comment]
Also in Card.xaml adjust the the Padding Setter to be like Microsoft Store which is:
`<Setter Property="Padding" Value="24" />`

instead of:
`<Setter Property="Padding" Value="8" />`

**Comment by ghost1372** [comment]
> Also in Card.xaml adjust the the Padding Setter to be like Microsoft Store which is: `<Setter Property="Padding" Value="24" />`
> 
> instead of: `<Setter Property="Padding" Value="8" />`

i will fix this soon
thank you.

**Comment by ghost1372** [comment]
> > > No the click event i can get from a custom button inside TitleContent in the Card. I need the gallery which is similar to what you already have for the MainLandingPage ([here](https://github.com/ghost1372/DevWinUI/blob/30a24aa157e755cd9c1bad64f5bd7a6dcb8fdc93/dev/DevWinUI.Controls/LandingPages/TileGallery.xaml)). But it should be able to expand into full screen and support Video (MediaPlayerElement) and Images.
> > 
> > 
> > Ah, now I understand. I’ve been planning to create Microsoft’s Carousel for quite a while, but the full-screen opening feature is something that you’ll need to implement yourself.
> 
> Isn't it possible to do that inside the control itself like it is for MessageBox or ContentDialog?

It’s possible, but it would become quite complex. I think you can have your own cards and, using connected animations, display your content (image or video) in another window. The WinUI Gallery has a few related examples. This is the simplest and best approach.

<img width="1033" height="727" alt="Image" src="https://github.com/user-attachments/assets/8e18c825-c80c-4d6c-9217-2e38eaabc04b" />

**Comment by ghost1372** [comment]
> Also fix the MessageBox documentation link.
> 
> Replace Current (404): https://ghost1372.github.io/DevWinUIControls/controls/messagebox
> 
> with: https://ghost1372.github.io/DevWinUIControls/controls/messageBox
> 
> Also there is some delay when using Smoke Layer Underlay compared to a native ContentDialog

Thanks,
the link has been fixed.
The Smoke Layer is created when the Dialog opens, not when it loads. Also, because we are using some opacity transitions, the delay is predictable.

**Comment by tinodin** [comment]
> > Also in Card.xaml adjust the the Padding Setter to be like Microsoft Store which is: `<Setter Property="Padding" Value="24" />`
> > instead of: `<Setter Property="Padding" Value="8" />`
> 
> i will fix this soon thank you.

Sorry to bother you but it seems like you forgot. You can update it in the next version, no rush.

**Comment by tinodin** [comment]
> I am also closing this issue because some of the requested features will be implemented in the carousel control.

@ghost1372 Is this carousel control going to be from you or WinUI?

**Comment by tinodin** [comment]
@ghost1372 Any updates on this?

**Comment by ghost1372** [comment]
> [@ghost1372](https://github.com/ghost1372) Any updates on this?

Not yet — there are a few seemingly simple but actually tricky aspects that I haven’t had time to research yet. For example, the infinite mode (so when reaching the last item, it loops back to the first one), and the display mode (currently, I think only one item can be visible at a time). I’m planning to implement top-center and bottom-left display modes.
There are also some other things, but I can’t recall them right now.

<img width="4096" height="2304" alt="Image" src="https://github.com/user-attachments/assets/7b61f49e-f7df-4b2d-8c29-07b5843f2c4f" />

**Comment by tinodin** [comment]
@ghost1372 Im working on porting the initial design I wanted from MS Store to DevWinUI, should it be called `Store Carousel 2` because its taken from MS Store or should it be called `MediaCarousel` / `ScreenshotCarousel`?

**Comment by ghost1372** [comment]
@tinodin Nice, Whatever you want, personally, I don’t agree with `ScreenshotCarousel`. 😁
